name: vylet
channels:
- conda-forge
- defaults
dependencies:
- python=3.8
- numpy
- pandas
- pip
- pip:
    - plotly
    - pygame==2.0.0
    - torch
    - gensim==4.2.0
    - faiss-cpu
    - jupyter
    - notebook
    - bs4
    - requests
    - nltk